server:
  port: 8082


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: himanshubector
    password: root


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# ddl-auto property will generate the table corr. to the entity

# No need to set the dialect and driver-class-name as well

